### ISSUE TITLE
Can I use xloil with 64-bit Python and 32-bit Excel ?

### ISSUE THREAD

**Issue by oscar6echo** [cunnane/xloil#100]
In a corp (immutable) setup I have:
+ x86_64 Win10 machine
+ miniconda 64-bit installed
+ Excel 32-bit.

Is there a way to use xloil with this setup ?

From the doc I [read](https://xloil.readthedocs.io/en/stable/xlOil_Python/GettingStarted.html#getting-started):
> **You must use the same bit-ness of python and Excel**. So if your Excel is 32-bit, you must install xloil using a 32-bit python distibution.

So I understand that this will not fly.  
Pls confirm / infirm / amend.

(Btw thx for the effort you put in sharing this lib :+1: )

**Comment by kousikpandey** [comment]
[https://xloil.readthedocs.io/en/stable/xlOil_Python/GettingStarted.html#getting-started](url)

"You must use the same bit-ness of python and Excel. So if your Excel is 32-bit, you must install xloil using a 32-bit python distibution."

**Comment by cunnane** [comment]
Unfortunately you are correct.  One of the key design decisions of xlOil was to keep it in-process - this means it is fast: the overhead very close to native C if you are manipulating numpy arrays.  It also means you can do callbacks like RTD functions, events and GUIs all in python.  To mix bit-ness function arguments and results would need to be serialized and transported to a outside process.  If you need this functionality, *xlwings* can do it, otherwise try to make a case to your IT department.  You may be able to install python locally in your AppData - it doesn't need admin permissions.
