### ISSUE TITLE
Working with ranges

### ISSUE THREAD

**Issue by talalvas** [cunnane/xloil#44]
Hello,
As a new library, i hope that you will appreciate some ideas to improve.

The work with slicing a `xlo.range` object is not very convenient.

To quote from the docs about ways to access and slice ranges:
```python
x[1, 1] # The *value* at (1, 1) as a python type: int, str, float, etc.
x[1, :] # The second row as another Range object
x[:-1, :-1] # A sub-range omitting the last row and column
```

It would be much more convenient if all the options above (including the first) will return range.
Also there is a problem with slicing one dim range:
```python
rng = xlo.range("A1:D1")
rng[0]  # Returns error, expected to return range "A1"
rng[0, :] # Returns range "A1" (The ', :' is redundant)
```

Another thing that will help a lot is to enable a way that will do the opposite of `to_com()` function.
In order to work with the more convenient object `xlo.Range` instead of `win32com.Range` (for slicing and more things that you've worked on), I find myself doing this action several times:
```python
rng = xlo.Range(other_range.Range.Address)
```

If it was possible to convert `win32com.Range` to `xlo.Range `in a simpler manner it would save a lot of coding.

Thanks!

**Comment by cunnane** [comment]
The reason that `range[1,1]` returns a value is to be consistent with how *numpy* and *pandas*  and indeed *list* slices work which seems like a very persuasive argument in python.  Similarly `rng[0]` if it returned anything at all, might be expected to iterate over the range values, so that `[x for x in rng]` and `[rng[i] for x in range(len(rng)]` 

It might be less surprising to extend the `range` property so that writing `my_range.range[1,1]` or `my_range.range[0]` always returns a range regardless of the slice?

Allowing the syntax `rng = xlo.Range(other_range)` will be easy (it would just call `Address` for you).

**Comment by talalvas** [comment]
Thank you 👍
