### ISSUE TITLE
Return type pandas.DataFrame: large numbers are returned incorrectly

### ISSUE THREAD

**Issue by ShieldTrade** [cunnane/xloil#63]
```
@ xlo.func()
def pd_dataframe_large_nubers() -> pd.DataFrame:
    rate_history = [
        {
            'symbol': 'BTC/USD:BTC',
            'fundingRate': 0.0001,
            'timestamp': 1693166400000, # mls
            },
        {
            'symbol': 'BTC/USD:BTC',
            'fundingRate': 0.0003,
            'timestamp': 1694114889000,
            }]
    df = pd.DataFrame(rate_history)
    return df
```
Timestamp large number are incorrectly returned. 

my `sys.maxsize` = 9223372036854770000

I tried the following with no result
`df = df.astype({"timestamp": np.int64})` and` df = df.astype({"timestamp": int})` .

I could do `df = df.astype({"timestamp": str})`. correct display but I could no longer use them as numbers-

If I use Sec instead of Mls,  smaller numbers are correctly returned-

**Comment by cunnane** [comment]
Excel natively only supports 32 bit integers, so you have a couple of
options: convert to a float or create a pandas Timestamp with millisecond
precision (which will end up being converted to an Excel date float)

I'll add some error or silently convert to float (with a warning since it
discards precision) to make this all less surprising.

**Comment by ShieldTrade** [comment]
You are absolutely right.
Excel 64 bit  just means Excel is compiled to run natively on 64-bit.

in any case I think [this](https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/data-types/long-data-type)  is misleading 

> Holds signed 64-bit (8-byte) integers ranging in value from -9,223,372,036,854,775,808 through 9,223,372,036,854,775,807 (9.2...E+18).

letting me think `vba long` and int64 are the same.

**Comment by cunnane** [comment]
Although VBA can handle 64-bit integers, they can't appear on a worksheet - try entering 9,233.... in a cell and it will be truncated to a float.

**Comment by ShieldTrade** [comment]
Correct. 

Excel spreadsheet, has  a limit for storing a number in a Cell, which is 15 digits (15 numbers) regardless of whether the numbers are decimal places. Excel call this “15 significant digits of precision”.

Remembering basic algebra. infinite numbers , such as π (3.1415….), exists. They would require infinite computer memory to be stored. This is the reason of the above limit. Excel will truncate ( not round) every number you enter in a cell to 15 digits.

I suggest everybody working with xlOil to refresh his/her knowledge of data types, 
Even if I have been using Excel and VBA extensively, when python and pandas come in to play thanks to xlOil, I realized how poor my Knowledge was.

I will post the main problems and errors I encounter hoping It will help

**Comment by cunnane** [comment]
To be fair, this limitation is imposed by the use of [double precision floating point](https://en.wikipedia.org/wiki/Double-precision_floating-point_format) rather than being intrinsic to Excel.  The designers could have used customised arbitrary precision arithmetic, but the performance would be horrible.  If you really need this, it would be possible in xlOil via the use of cache objects (possibly setting the cache tag to equal the string representation of the number to aid useability), but you'd need to define custom functions for all arithmetic operations.
