### ISSUE TITLE
Development experience improvement

### ISSUE THREAD

**Issue by lukedays** [cunnane/xloil#8]
I was talking to some colleagues that use xlwings today and are experimenting with xloil, together with my experience.
Some suggestions:
- To have a configuration ribbon like xlwings, such that adding/changing modules in different paths would be simpler. Maybe a CLI should be an easier workaround (`xloil add module`, etc)

- Sometimes when several Python versions are installed, conflicts happen (`Failed LoadLibrary for xlOil_Python3.xx`). The way I solved is to include the version in the .ini file (`xlOilPythonVersion`), but maybe this could be simpler/clearer (maybe a default interpreter selector during `xloil install`, similar to VSCode).

**Comment by cunnane** [comment]
Agree, I've thought about a ribbon before and it's about time I got around to it!  When you run `xloil install` it should hard code the paths in xlOil.ini to whatever python version is being executed... however that this means changing the version is a bit manual.  If you have any python directories in your system environment variables (not recommended) then this may well conflict with xlOil's settings.

**Comment by cunnane** [comment]
I'm going to tentatively close this as it's largely addressed in the xlOil Ribbon in v0.15.  I've gone with the ribbon rather than the CLI but could add the feature there if it's desired.

(I've just realised that the version selector allows your to select environments where xlOil is not installed - will add a warning for this)
