### ISSUE TITLE
xloil seems to break the Excel Offset method

### ISSUE THREAD

**Issue by renfrowjay** [cunnane/xloil#95]
Here's a simple py script demonstrating the issue I have with the Offset method:

@xlo.func(macro=True, command=True)
def offset_activecell():
    app = xlo.app()
    app.ActiveCell.Offset(0,0).Value = 'test'

I wasn't able to find the xloil method of getting the active cell, so I reverted to using the Excel.Application object to get to the ActiveCell method. I've tested that ActiveCell is working properly by reading the value in the active cell (not demo'd here). However when I try to use the Offset method as above, it seems to think the origin is one row above and one column to the left. It also will not accept negative numbers as arguments to Offset. It consistently performs this way if I move the active cell around the worksheet also.

Here's a screen shot showing where it is writing the 'test' string:
<img width="213" alt="Excel Offset Issue" src="https://github.com/cunnane/xloil/assets/7347549/4d83da0f-cd8c-431c-8ecc-c7e81548071b">

On another thought, just for my information, is there an xloil method to get the active cell?

**Comment by cunnane** [comment]
xlOil provides a number of objects, e.g. Range, Worksheet, which correspond to the Application API in VBA/COM.  When you access a property of one of these objects with CamelCase, the request is handled by the *pywin32* library interacting directly with Excel's COM interface.  So the issue here lies in the *pywin32* library and can't be directly fixed by xlOil.

There's no method to get the active cell in xlOil, but it's straightforward to add and I'll include it in the next release.

In the meantime, you can convert the COM object to xlOil with `r = xlo.Range(app.ActiveCell.Address)`.  xlOil does not provide an *offset* function (although again it's easy to add) and instead has this functionality in the *range* function, so to write a value to cell above and to the left, use `r.range(-1, -1, -1, -1).value = "hello"`

**Comment by renfrowjay** [comment]
Thanks for the clarification. I ran a test directly with pywin32 (no xloil) and pywin32 is where the problem is.

**Comment by cunnane** [comment]
I'll let you know when I've added the new function `xlo.active_cell()` to provide a better approach

**Comment by renfrowjay** [comment]
Thanks, much appreciated!

Jay
